[workspace]
members = [
    "harper-cli",
    "harper-core",
    "harper-ls",
    "harper-comments",
    "harper-wasm",
    "harper-tree-sitter",
    "harper-html",
]
resolver = "2"

[profile.release]
opt-level = 3
strip = true
