name: Build Web

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: redhat-actions/buildah-build@v2
        with:
          image: web
          layers: false
          containerfiles: |
            Dockerfile
